version: "3.3"
services:
  web:
    image: fischerfredl/bp-geo:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MONGODB_HOST: mongo
      MONGODB_DB: bp-geo
    ports:
      - "5010:80"

  mongo:
    image: mongo:3.4
    deploy:
      restart_policy:
        condition: on-failure
    ports:
     - "27017:27017"
