version: "3.3"
services:
  web:
    image: fischerfredl/bp-geo:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MONGODB_HOST: mongo
      MONGODB_DB: bp-geo
    secrets:
      - mongodb_username
      - mongodb_password
    ports:
      - "5010:80"

  mongo:
    image: mongo:3.4
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - mongodb_admin_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongodb_admin_password"
    ports:
     - "27017:27017"

secrets:
  mongodb_admin_password:
    file: instance/mongodb_admin_password
  mongodb_username:
    file: instance/mongodb_username
  mongodb_password:
    file: instance/mongodb_password
