version: "3.1"
services:
  mongo:
    image: mongo:3.4
    deploy:
      restart_policy:
        condition: on-failure
    ports:
     - "27017:27017"

  web:
    image: fischerfredl/bp-geo:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"